export const GET_INITIALS_REQUEST = 'GET_INITIALS_REQUEST'
export const GET_INITIALS_SUCCESS = 'GET_INITIALS_SUCCESS'
export const GET_INITIALS_FAIL = 'GET_INITIALS_FAIL'

export const INITIAL_ADD_REQUEST = "INITIAL_ADD_REQUEST"
export const INITIAL_ADD_SUCCESS = "INITIAL_ADD_SUCCESS"
export const INITIAL_ADD_FAIL = "INITIAL_ADD_FAIL"
export const INITIAL_ADD_RESET = "INITIAL_ADD_RESET"

export const INITIAL_DELETE_REQUEST = "INITIAL_DELETE_REQUEST"
export const INITIAL_DELETE_SUCCESS = "INITIAL_DELETE_SUCCESS"
export const INITIAL_DELETE_FAIL = "INITIAL_DELETE_FAIL"
export const INITIAL_DELETE_RESET = "INITIAL_DELETE_RESET"
